In [1]:
import numpy as np

以下のような行列A, Bを考えます。
$$ A = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6 \\
      7 & 8 & -9 \\
    \end{array}
  \right],
  B = \left[
    \begin{array}{ccc}
      0 & 2 & 1 \\
      0 & 2 & -8 \\
      2 & 9 & -1 \\
    \end{array}
  \right] $$
行列の内積A*Bを手計算で解きなさい。

## 【問題1】行列式を手計算する
行列の積ABの各要素cは下記の式で計算できる。  
$$
c_{ij} = \sum_k (a_{ik}b_{kj})
$$
よって
$$
C = AB = \left[
    \begin{array}{ccc}
      6& 29 & -20 \\
      12 & 52 & 38 \\
      -18 & -51 & -48 \\
    \end{array}
  \right]
 $$

## 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。  
これらを使い行列積を計算してください。

In [3]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [5]:
#np.mutmul
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [6]:
#np.dot
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [8]:
#@演算子
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【問題3】ある要素の計算を実装
$(AB)_{00}$の計算

In [10]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [11]:
c = np.zeros((a_ndarray.shape[0], b_ndarray.shape[1]))
for i in range(a_ndarray.shape[1]):
    c[0, 0] += a_ndarray[0, i] * b_ndarray[i, 0]
print(c)

[[6. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## 【問題4】行列式を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。  
行列AとBを引数に受け取り、行列積を返す関数としてください。  
行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

In [12]:
def multiply(A, B):
    C = np.zeros([A.shape[0], B.shape[1]])
    for row in range(A.shape[0]):
        for col in range(B.shape[1]):
            for i in range(A.shape[1]):
                C[row, col] += A[row, i] * B[i, col]
    return C

In [13]:
multiply(a_ndarray, b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。  
また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。  
if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [23]:
def multiply(A, B):
    if A.shape[1] != B.shape[0]:
        print('Error!')
        print(f'shapes {A.shape} and {B.shape} not aligned: {A.shape[1]} (dim 1) != {B.shape[0]} (dim 0)')
        return
    
    C = np.zeros([A.shape[0], B.shape[1]])
    for row in range(A.shape[0]):
        for col in range(B.shape[1]):
            for i in range(A.shape[1]):
                C[row, col] += A[row, i] * B[i, col]
    return C

In [28]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [29]:
multiply(d_ndarray, e_ndarray)

Error!
shapes (2, 3) and (2, 3) not aligned: 3 (dim 1) != 2 (dim 0)


In [30]:
multiply(a_ndarray, b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります

In [31]:
multiply(d_ndarray, np.transpose(e_ndarray))

array([[ 46.,  -4.],
       [-34.,  73.]])

In [32]:
multiply(d_ndarray, e_ndarray.T)

array([[ 46.,  -4.],
       [-34.,  73.]])