## 【課題1】内積を手計算しよう
以下のような行列A, Bを考えます。
$$ A = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6 \\
      7 & 8 & -9 \\
    \end{array}
  \right],
  B = \left[
    \begin{array}{ccc}
      0 & 2 & 1 \\
      0 & 2 & -8 \\
      2 & 9 & -1 \\
    \end{array}
  \right] $$
行列の内積A*Bを手計算で解きなさい。

In [3]:
AB = [[6, 29, -20],
      [12, 52, 38],
      [-18, -51, -48]]

## 【課題2】1次元配列の内積をfor文で計算しよう
これ以降の課題は**NumPyを使って**解いてください。  
【課題1】では手計算してもらいました。一つ一つの演算はさほど難しくありませんが、演算数は多くかなり面倒くさかったと思います。  
この演算をpythonを使って実装するとどうなるのでしょうか？  
手計算する際には、まず行列Aの1行目と行列Bの1列目に注目したと思います。そして、  
- 行列Aの(0,0)の要素と行列Bの(0,0)の要素を掛け合わせる
- 行列Aの(0,1)の要素と行列Bの(1,0)の要素を掛け合わせる
- 行列Aの(0,2)の要素と行列Bの(2,0)の要素を掛け合わせる
- それらの値を全て足し合わせる 

というフローを得て、ようやく一つ目の要素が求まるわけです。  
まずは、ご自身で配列のindexを指定し、  
- 行列Aの(0,0)の要素と行列Bの(0,1)の要素を掛け合わせる
- 行列Aの(0,1)の要素と行列Bの(1,1)の要素を掛け合わせる
- 行列Aの(0,2)の要素と行列Bの(2,1)の要素を掛け合わせる
- それらの値を全て足し合わせる

のフローをfor文を使って計算してください。

In [5]:
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
AB_01 = 0

for i in range(3):
    AB_01 += A[0,i] * B[i,1]
AB_01

29

## 【課題3】多次元配列の内積をfor文で計算しよう
【課題2】ではA*Bの(0,0)だけ計算するコードを実装してもらいましたが、全要素を求めるにはどうしたら良いでしょうか？  
行列A*Bの(0,1)を求めるには  
行列Aのインデックスは固定（0行目を選択したまま）で、行列Bのインデックスを0列目から1列目に指定しなおせば良いわけです。理解できない方は、手計算でのフローを思い出してください！  
- 行列Aの(0,0)の要素と行列Bの(0,1)の要素を掛け合わせる
- 行列Aの(0,1)の要素と行列Bの(1,1)の要素を掛け合わせる
- 行列Aの(0,2)の要素と行列Bの(2,1)の要素を掛け合わせる
- 1、2、3で求めた値を足し合わせる

とすればA*Bの(0,1)の要素が求まります。
このように同じ計算を順次インデックスを増やして行けば、全要素の計算ができます。

In [6]:
AB = np.zeros([3, 3])

for i in range(3):
    for j in range(3):
        for k in range(3):
            AB[i, j] += A[i,k] * B[k,j]
AB

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## 【課題4】内積をnp.dotで計算しよう
【課題3】ではfor文を使うことで、内積を計算していただきましたが、行列の内積演算の度にこのようにfor文の処理を何回も実装しなくてもはならないのでしょうか  
当然そんなことはなく、実はみなさんがやっていただいた処理はnumpyのメソッドですでに用意されています。
np.dot(A,B)と計算すると、【課題3】で計算していただいたことが一瞬でできます。  
np.dot(A,B)を計算して、【課題3】と同じになることを試してください。  

In [7]:
import numpy as np
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
np.dot(A, B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【課題5】内積ができないときはどうするか
以下のような例を考えます。
$$ A = \left[
     \begin{array}{ccc}
     -1 & 2 & 3 \\
      4 & -5 & 6 \\
     \end{array}
     \right], 
   B = \left[
     \begin{array}{ccc}
     -9 & 8 & 7 \\
      6 & -5 & 4 \\
     \end{array}
     \right] $$
     
行列A\*Bを計算しようとすると、エラーが出て計算できません。なぜエラーが出るのか理由を記載してください。  
そして、行列A、Bのどちらかに**ある操作**をするとエラーが出ずに計算できます。  
自分で**ある操作**を施し、内積を計算してください。

In [12]:
A = np.array([[-1, 2, 3], [4, -5, 6]])
B = np.array([[-9, 8, 7], [6, -5, 4]])
# np.dot(A, B)はAの行数とBの列数が等しくないため計算できない

#AとBの内積を計算する
#Aの転置行列を取る
AB = np.dot(A.T, B)
AB

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])